# Generated by Django 5.2.1 on 2025-07-09 22:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0014_alter_workouts_day'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workouts',
            name='workout_image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
